### ISSUE TITLE
NullPointerException when classes don't share same package

### ISSUE THREAD

**Issue by schw4rzlicht** [fujaba/fulibYaml#2]
When creating `YamlIdMap` instances, we need to specify the package name of the model we want to serialize. This leads to `ClassNotFoundException` when the model references classes outside of the specified package: 

https://github.com/fujaba/fulibYaml/blob/de72f3aafcd1556078710d543829840a3243b859/src/main/java/org/fulib/yaml/ReflectorMap.java#L55-L72

The exception is caught but `null` is returned eventually, leading to `NullPointerException`: 

https://github.com/fujaba/fulibYaml/blob/de72f3aafcd1556078710d543829840a3243b859/src/main/java/org/fulib/yaml/YamlIdMap.java#L1053-L1055

I'd suggest either
* to throw a custom `RuntimeException` when catching `ClassNotFoundException` (or rethrow it for that matter) since this is an implementation-bug of the library user or
* to get the package names from the classes at runtime to avoid the problem altogether

**Comment by azuendorf** [comment]
fixed as proposed in the 2019SummerTerm branch. 
Becomes master, soon.

**Comment by schw4rzlicht** [comment]
I still see the issue when running tests from #3 because `getReflector()` still returns `null` when `org.eclipse.emf.ecore.EClass` could not be loaded: https://github.com/fujaba/fulibYaml/blob/675d592e57a1cd9831c02976927455e224cbdf75/src/main/java/org/fulib/yaml/ReflectorMap.java#L87
